/*
* generated by Xtext
*/
package www.ubx.ch.ui.contentassist;

import www.ubx.ch.ui.contentassist.AbstractOpenAirProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class OpenAirProposalProvider extends AbstractOpenAirProposalProvider {

}
