/*
* generated by Xtext
*/
package www.ubx.ch.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class OpenAirDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

//	public String text(IEObjectDescription ele) {
//		  return "my "+ele.getName();
//		}

	
	/*
	//Labels and icons can be computed like this:
	
	 
    String image(IEObjectDescription ele) {
      return ele.getEClass().getName() + ".gif";
    }	 
*/

}
