/*
 * generated by Xtext
 */
package www.ubx.ch.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import www.ubx.ch.openAir.Airspace;
import www.ubx.ch.openAir.OpenAir;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class OpenAirLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public OpenAirLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(Airspace rule) {
		return "->" + rule.getThedef().getName().getName();
	}

	/*
	 * //Labels and icons can be computed like this:
	 * 
	 * String text(MyModel ele) { return "my "+ele.getName(); }
	 * 
	 * String image(MyModel ele) { return "MyModel.gif"; }
	 */
}
