/*
 * generated by Xtext
 */
package www.ubx.ch;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OpenAirRuntimeModule extends www.ubx.ch.AbstractOpenAirRuntimeModule {

}
