/*
* generated by Xtext
*/
package www.ubx.ch.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class OpenAirTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
