/*
 * generated by Xtext
 */
package www.ubx.ch.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OpenAirUiModule extends www.ubx.ch.ui.AbstractOpenAirUiModule {
	public OpenAirUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
